# Generated by Django 4.2.16 on 2024-11-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth0_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(default='user', max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('mentor', 'Mentor')], max_length=50)),
                ('area_of_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(default='media/images/defaults/Default_pfp.svg.png', upload_to='pfp')),
            ],
        ),
    ]
