# Generated by Django 4.2.16 on 2024-11-24 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_admin_alter_room_area_of_interest_and_more'),
        ('users', '0001_initial'),
        ('core', '0004_post_is_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('room', 'Room'), ('post', 'Post'), ('custom', 'Custom')], help_text='Type of the notification.', max_length=20)),
                ('content', models.TextField(help_text='Custom notification message.')),
                ('is_read', models.BooleanField(default=False, help_text='True if the notification has been read.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, help_text='Message associated with the notification (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.message')),
                ('post', models.ForeignKey(blank=True, help_text='Post associated with the notification (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.post')),
                ('recipient', models.ForeignKey(help_text='The user who receives the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile')),
                ('room', models.ForeignKey(blank=True, help_text='Room associated with the notification (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.room')),
                ('sender', models.ForeignKey(blank=True, help_text='The user who triggered the notification (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='users.userprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.userprofile')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
