# Generated by Django 4.2.16 on 2024-11-24 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the room.', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Unique slug for the room, auto-generated from name.', unique=True)),
                ('private', models.BooleanField(default=False, help_text='True for private rooms, False for public/group rooms.')),
                ('profile_pic', models.ImageField(default='images/defaults/Default_pfp.svg.png', help_text="Room's profile picture.", upload_to='pfp')),
                ('area_of_interest', models.CharField(blank=True, help_text='Topic of interest for public/group rooms.', max_length=255, null=True)),
                ('admin', models.ForeignKey(blank=True, help_text='Admin for private rooms (Django User).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_admin_rooms', to=settings.AUTH_USER_MODEL)),
                ('group_admin', models.ForeignKey(blank=True, help_text='Admin for group rooms (UserProfile).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_admin_rooms', to='users.userprofile')),
                ('users', models.ManyToManyField(help_text='Participants of the room.', related_name='rooms', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.userprofile')),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
    ]
