# Generated by Django 4.2.16 on 2024-11-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area_of_interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='profile_pic',
            field=models.ImageField(default='media/images/defaults/Default_pfp.svg.png', upload_to='pfp'),
        ),
    ]
