# Generated by Django 4.2.16 on 2024-11-19 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_room_area_of_interest_room_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Admin for private rooms (Django User).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_admin_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='area_of_interest',
            field=models.CharField(blank=True, help_text='Topic of interest for public/group rooms.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='group_admin',
            field=models.ForeignKey(blank=True, help_text='Admin for group rooms (UserProfile).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_admin_rooms', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='Name of the room.', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=False, help_text='True for private rooms, False for public/group rooms.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='profile_pic',
            field=models.ImageField(default='images/defaults/Default_pfp.svg.png', help_text="Room's profile picture.", upload_to='pfp'),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique slug for the room, auto-generated from name.', unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(help_text='Participants of the room.', related_name='rooms', to='users.userprofile'),
        ),
    ]
